l_spanish:
  impart_values.0001.t:0 "Inculcare una lezione di vita"
  impart_values.0001.desc:0 "#italic Ah, essere giovani, pieni di vitalità. L'intero mondo di fronte a voi, in attesa di essere scoperto. E la vostra personalità, un mistero per voi stessi.#!\n\nMi ritrovo a riflettere sulla volubilità della giovinezza quando entra [recipient.GetTitledFirstName], il mio [recipient.Custom('InsultAdjective')] [ROOT.Char.Custom2('RelationToMeShort', recipient)], con la sua solita mancanza di attenzione.\n\nVedendo [recipient.GetSheHe] si accende qualcosa dentro di me: #bold Insegnerò a questo bambino una lezione su ciò che è veramente importante nella vita.#!"
  already_imparted_lesson_desc:0 "Hai già cercato di insegnare a [CHARACTER.GetShortUINameNoTooltip] cosa valorizzare nella vita."
  impart_values.0001.diligent:0 "[recipient.GetSheHe] imparerà che il duro lavoro costante lo aiuterà sempre."
  impart_values.0001.lazy:0 "[recipient.GetFirstName] deve imparare a lasciare che siano gli altri a occuparsi delle cose."
  impart_values.0001.cynical:0 "[recipient.GetSheHe] deve imparare a mettere sempre in dubbio le motivazioni degli altri."
  impart_values.0001.zealous:0 "Insegnerò a [recipient.GetSheHe] che la fede è di importanza primaria."
  impart_values.0001.brave:0 "[recipient.GetFirstName] imparerà ad essere senza paura di qualsiasi avversario."
  impart_values.0001.craven:0 "Nascondersi da tutte le paure è una saggezza da tenere a mente."
  impart_values.0001.calm:0 "Insegnerò a [recipient.GetFirstName] l'importanza di rimanere calmo."
  impart_values.0001.wrathful:0 "Insegnerò a [recipient.GetSheHe] a lasciarsi guidare dalla rabbia e dalla furia."
  impart_values.0001.chaste:0 "[recipient.GetFirstName] dovrebbe respingere qualsiasi tentazione dei desideri naturali."
  impart_values.0001.lustful:0 "[recipient.GetFirstName] dovrebbe imparare ad abbracciare i propri desideri naturali."
  impart_values.0001.content:0 "Insegnerò a [recipient.GetSheHe] ad essere contento di ciò che [recipient.GetSheHe] possiede già."
  impart_values.0001.ambitious:0 "Insegnerò a [recipient.GetSheHe] l'importanza dell'ambizione."
  impart_values.0001.fickle:0 "Insegnerò a [recipient.GetSheHe] che una mente mutevole è un tratto desiderabile."
  impart_values.0001.stubborn:0 "[recipient.GetSheHe] imparerà a non indietreggiare mai di fronte a qualsiasi opposizione."
  impart_values.0001.forgiving:0 "[recipient.GetSheHe] imparerà l'importanza di mostrare misericordia agli altri."
  impart_values.0001.vengeful:0 "Insegnerò a [recipient.GetSheHe] a non dimenticare le persone che gli fanno del male."
  impart_values.0001.generous:0 "Mostrerò a [recipient.GetSheHe] che gli atti di carità hanno un significato senza fine."
  impart_values.0001.greedy:0 "Una stretta presa sulla propria borsa è sempre una lezione valida da imparare."
  impart_values.0001.gregarious:0 "Mostrerò a [recipient.GetSheHe] le gioie della compagnia degli altri."
  impart_values.0001.shy:0 "Insegnerò a [recipient.GetSheHe] i benefici pacifici di stare da soli."
  impart_values.0001.honest:0 "[recipient.GetSheHe] imparerà che verità e sincerità sono valori primari."
  impart_values.0001.deceitful:0 "Insegnerò a [recipient.GetFirstName] a mentire così facilmente quanto respirare."
  impart_values.0001.humble:0 "Una vita di modestia è un semplice piacere che [recipient.GetFirstName] può imparare."
  impart_values.0001.arrogant:0 "[recipient.GetSheHe] imparerà che il proprio senso di autovalutazione è più importante di tutto."
  impart_values.0001.just:0 "Insegnerò a [recipient.GetSheHe] a rispettare le leggi degli dei e degli uomini."
  impart_values.0001.arbitrary:0 "Dovrebbero imparare a fare le proprie cose, indipendentemente dagli altri."
  impart_values.0001.patient:0 "L'importanza della pazienza è ciò che insegnerò a [recipient.GetSheHe]."
  impart_values.0001.impatient:0 "Insegnerò a [recipient.GetSheHe] a diventare irrequieto di fronte al ritardo dei risultati."
  impart_values.0001.temperate:0 "[recipient.GetSheHe] imparerà che tutto dovrebbe essere preso con moderazione."
  impart_values.0001.gluttonous:0 "[recipient.GetFirstName] dovrebbe abbracciare l'abbondanza di tutte le cose piacevoli."
  impart_values.0001.trusting:0 "[recipient.GetSheHe] imparerà a fidarsi di coloro che gli stanno intorno."
  impart_values.0001.paranoid:0 "[recipient.GetFirstName] deve imparare a guardarsi sempre alle spalle."
  impart_values.0001.compassionate:0 "[recipient.GetFirstName] imparerà che la compassione è più importante di tutto."
  impart_values.0001.callous:0 "Disprezzare i problemi degli altri servirà bene a [recipient.GetFirstName]."
  impart_values.0001.sadistic:0 "Insegnerò a [recipient.GetSheHe] il piacere di ferire gli altri."
  impart_values.0001.rude:0 "Insegnerò a [recipient.GetSheHe] a dire ciò che pensa, non importa quanto brusco."
  impart_values.0001.honorable:0 "Insegnerò a [recipient.GetFirstName] a tenere in alto i propri principi morali."
  impart_values.0001.ruthless:0 "[recipient.GetSheHe] imparerà ad essere spietato per raggiungere i propri obiettivi."
  impart_values.0001.authoritative:0 "Insegnerò a [recipient.GetSheHe] l'importanza di essere autorevole."
  impart_values.0001.inquisitive:0 "[recipient.GetSheHe] imparerà il valore della ricerca della conoscenza."
  impart_values.0001.backout:0 "Poco male, non credo che [recipient.GetSheHe] sia pronto."
  impart_values_lesson_ignored_title:0 "Lezione Ignorata"
  impart_values_lesson_ignored_desc:0 "[recipient.GetShortUINameNoTooltip] non ha mostrato alcun interesse nelle tue lezioni."
  impart_values_lesson_success_title:0 "Successo della Lezione"
  impart_values_lesson_success_desc:0 "[recipient.GetShortUINameNoTooltip] ha preso a cuore le tue lezioni e ha acquisito il tratto [recipient.Custom('TraitLearned')]."
  impart_values_lesson_failure_title:0 "Fallimento della Lezione"
  impart_values_lesson_failure_desc:0 "[recipient.GetShortUINameNoTooltip] si è ribellato alle tue lezioni e ha acquisito il tratto [recipient.Custom('TraitLearned')]."
