l_spanish:
  at_artifact_price_qwa_desc: "Qualità e Ricchezza"
  at_artifact_price_durability_desc: "Durabilità"
  at_artifact_price_destroy_desc: "Comune o Capolavoro"
  at_artifact_price_unique_desc: "Unico"
  at_artifact_ask_price_player_desc: "Margine di Profitto"
  at_artifact_ask_price_ai_greed_desc: "Avidità del Venditore"
  at_artifact_bid_price_ai_greed_desc: "Avidità dell'Acquirente"